name: SonarQube Analysis with Docker

on:
  push:
    branches: [ main ]

jobs:
  sonarqube:
    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Run SonarQube Analysis with Docker
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      run: |
        # Utilise Docker pour analyser
        docker run --rm \
          -v "$PWD:/usr/src" \
          -e SONAR_HOST_URL="$SONAR_HOST_URL" \
          -e SONAR_TOKEN="$SONAR_TOKEN" \
          -e SONAR_SCANNER_OPTS="-Dsonar.projectKey=user-management" \
          sonarsource/sonar-scanner-cli:latest
